### ISSUE TITLE
[General] - Longer Dashed Border

### ISSUE THREAD

**Issue by tinyherocarrot** [outputfield/outputfield#41]
### Background

Dashed borders are used across the website to demarcate different sections and focus user attention. We need dashed borders with longer dashes than native dashed borders offers. Native CSS properties don't support the customization of border-style. Therefore, we must use a trick with an SVG image inside background-image property.

This should only require updating `global.css` (classes marked with "TODO"). The class for a full border ("border-dashed-long") is already written, but the remaining variations may require using SVG "line" instead of "rect". You can test the result using the "Try it" section under MDN's background-image [page](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image).

Create a branch off of "outputfield/dev" for this task.

### Acceptance Criteria

Dashed borders on the following pages should match [Figma](https://www.figma.com/file/nOVN00JxxMrwsn8sGB6oVW/OF-Overview?node-id=0%3A1&t=UHQKUDodFtR30vOG-0):
- /artists
- /create-account

**Comment by KalisaFalzone** [comment]
Dashes look different when rendered in Figma (left) vs. Chrome:
<img width="841" alt="differenceInDashedStyle" src="https://user-images.githubusercontent.com/10011532/222840122-319e5117-c029-48bd-8c0e-97928d504ae5.png">

But the css is the same for both:
<img width="1508" alt="SameCSSFigmaVSChrome" src="https://user-images.githubusercontent.com/10011532/222840154-c53a9ad7-1f61-473e-a2be-20dbb26707b0.png">

**Comment by KalisaFalzone** [comment]
We met with Brenden today and are going to table this for now and re-visit design discrepancies after functionality is working.
