### ISSUE TITLE
Allow Admin to Approve/Reject applications through Discord reactions

### ISSUE THREAD

**Issue by mtham8** [outputfield/outputfield#64]
* Should be allow admin users to approve/reject pending applications through reacting in a Discord channel

* If application is approved - it should add a row to the ApplicationStatuses table (status = `APPROVED`)
* If application is rejected - it should add row to the ApplicationStatuses table (status = `REJECTED`)

**Comment by KalisaFalzone** [comment]
What reactions qualify as approval? Any emoji reaction? Does it need to un-approve if the reaction is taken off?
